import type { AppConfig } from './types'

export const siteConfig: AppConfig = {
  brand: {
    name: 'Sua Casa Leblon',
    whatsapp: '5521995360322',
  },
  pricing: {
    discount_pct: 0.14,
    cleaning_fee: 150,
  },
  rules: {
    min_nights_default: 1,
    min_nights_fri_sat: 2,
    max_checkout_date: '2026-12-31',
    overrides: [],
  },
  properties: [
    {
      code: '103',
      title: 'Leblon 103',
      subtitle: 'Studio reformado • 2 hóspedes • A 3 min da praia',
      max_guests: 2,
      base_guests: 2,
      extra_per_guest_per_night: 0,
      docs_required: false,
      demo_beyond_nightly: 600,
      images: ['/images/103/main.jpeg'],
    },
    {
      code: '403',
      title: 'Leblon 403',
      subtitle: 'Loft com mezanino • Até 4 hóspedes • Docs via WhatsApp',
      max_guests: 4,
      base_guests: 2,
      extra_per_guest_per_night: 75,
      docs_required: true,
      demo_beyond_nightly: 600,
      images: ['/images/403/main.jpeg'],
    },
    {
      code: '102',
      title: 'Leblon 102',
      subtitle: 'Studio completo • 2 hóspedes • Com máquina de lavar',
      max_guests: 2,
      base_guests: 2,
      extra_per_guest_per_night: 0,
      docs_required: false,
      demo_beyond_nightly: 600,
      images: ['/images/102/main.jpeg'],
    },
    {
      code: '303',
      title: 'Leblon 303',
      subtitle: '3 quartos • Até 6 hóspedes • Ideal para famílias',
      max_guests: 6,
      base_guests: 4,
      extra_per_guest_per_night: 100,
      docs_required: false,
      demo_beyond_nightly: 600,
      images: ['/images/303/main.jpeg'],
    },
    {
      code: '334A',
      title: 'Leblon 334A',
      subtitle: 'Studio moderno • Até 3 hóspedes • Docs via WhatsApp',
      max_guests: 3,
      base_guests: 2,
      extra_per_guest_per_night: 80,
      docs_required: true,
      demo_beyond_nightly: 600,
      images: ['/images/334A/main.jpeg'],
    },
  ],
}
